#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Build parent-variable SHAP tables and mechanism-writing templates.

This script reads the stable SHAP feature CSV files generated by
05_Shap/plot_shap_stability.py, merges transformed/related child features into
scientifically interpretable parent variables, and writes auditable tables and
parent-level plots for core or auxiliary validated tasks.

Important:
- SHAP describes model dependence, not causality.
- Correlated transforms can split attribution. The script therefore reports
  both SUM importance and conservative MAX-child importance, and ranks parents
  by the conservative MAX-child importance.
- Direction labels describe average SHAP-output direction only. They do not
  establish a monotonic physical relationship; dependence plots are required.
"""
from __future__ import annotations

import argparse
import json
import math
import re
import sys
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import numpy as np
import pandas as pd

try:
    import matplotlib.pyplot as plt
except Exception as exc:  # pragma: no cover
    raise RuntimeError("matplotlib is required to create parent-variable figures") from exc


DEFAULT_TASKS = ["LOI", "PHRR", "THR", "UL94_V0"]
STABLE_LEVEL_ORDER = {"High": 2, "Medium": 1, "Low": 0}


TASK_META: Dict[str, Dict[str, str]] = {
    "LOI": {
        "target_cn": "极限氧指数（LOI）",
        "objective": "max",
        "positive_output_cn": "提高LOI预测值",
        "negative_output_cn": "降低LOI预测值",
    },
    "PHRR": {
        "target_cn": "峰值热释放速率（PHRR）",
        "objective": "min",
        "positive_output_cn": "提高PHRR预测值",
        "negative_output_cn": "降低PHRR预测值",
    },
    "THR": {
        "target_cn": "总热释放量（THR）",
        "objective": "min",
        "positive_output_cn": "提高THR预测值",
        "negative_output_cn": "降低THR预测值",
    },
    "UL94_V0": {
        "target_cn": "UL-94 V-0概率",
        "objective": "max",
        "positive_output_cn": "提高V-0预测概率",
        "negative_output_cn": "降低V-0预测概率",
    },
    "Tg": {
        "target_cn": "玻璃化转变温度（Tg）",
        "objective": "max",
        "positive_output_cn": "提高Tg预测值",
        "negative_output_cn": "降低Tg预测值",
    },
    "TS_MPa": {
        "target_cn": "拉伸强度（TS）",
        "objective": "max",
        "positive_output_cn": "提高TS预测值",
        "negative_output_cn": "降低TS预测值",
    },
}


DESCRIPTOR_CN = {
    "LogP": "脂水分配/疏水性",
    "TPSA": "拓扑极性表面积",
    "HBA": "氢键受体数",
    "HBD": "氢键供体数",
    "MolWt": "分子量",
    "HeavyAtomCount": "重原子数",
    "RotBonds": "可旋转键数",
    "FractionCSP3": "sp3碳比例",
    "AromaticRings": "芳香环数",
    "RingCount": "总环数",
    "BalabanJ": "Balaban拓扑指数",
}


def _clean_text(value: object) -> str:
    return "" if pd.isna(value) else str(value).strip()


def _strip_transform_suffixes(feature: str) -> Tuple[str, List[str]]:
    """Remove repeated mathematical transform suffixes and return audit tags."""
    s = feature.strip()
    transforms: List[str] = []
    suffixes = [
        (r"_sqrt$", "sqrt"),
        (r"_sq$", "square"),
        (r"_log1p$", "log1p"),
        (r"_log$", "log"),
        (r"_cube$", "cube"),
        (r"_abs$", "absolute"),
    ]
    changed = True
    while changed:
        changed = False
        for pattern, label in suffixes:
            if re.search(pattern, s, flags=re.I):
                s = re.sub(pattern, "", s, flags=re.I)
                transforms.append(label)
                changed = True
                break
    return s, transforms


def _normalize_base_token(token: str) -> str:
    s = token.strip()
    s = re.sub(r"\s*wt%$", "", s, flags=re.I)
    s = s.replace("_wt%", "")
    s = re.sub(r"__+", "_", s)
    return s.strip("_")


def _descriptor_label(desc: str) -> Tuple[str, str]:
    desc = desc.strip("_")
    cn = DESCRIPTOR_CN.get(desc, desc)
    return desc, cn


def _target_display(token: str) -> str:
    key = token.strip().lower()
    return {
        "loi": "LOI",
        "phrr": "PHRR",
        "thr": "THR",
        "tg": "Tg",
        "ts": "TS",
        "ts_mpa": "TS",
    }.get(key, token)


def map_feature_to_parent(feature: str, feature_group: str) -> Dict[str, str]:
    """Map one engineered feature to a parent variable and interpretation key."""
    raw = feature.strip()
    base, transforms = _strip_transform_suffixes(raw)
    base_norm = _normalize_base_token(base)
    transform_text = ",".join(transforms) if transforms else "none"

    result = {
        "parent_variable": base_norm,
        "parent_variable_cn": base_norm,
        "parent_feature_group": feature_group,
        "mapping_type": "direct",
        "transform_tags": transform_text,
        "mechanism_key": "other",
        "mapping_note": "Direct mapping; review manually if used in the manuscript.",
    }

    # Fingerprints: keep each bit separate until RDKit substructure mapping is done.
    m = re.match(r"^(main|co|curing)_(morgan_r\d+|maccs)_(\d+)$", base_norm, flags=re.I)
    if m:
        scope, fp_type, bit = m.groups()
        scope_en = {"main": "Main FR", "co": "Co-FR", "curing": "Curing agent"}[scope.lower()]
        scope_cn = {"main": "主阻燃剂", "co": "协同阻燃剂", "curing": "固化剂"}[scope.lower()]
        result.update(
            parent_variable=f"{scope_en} {fp_type.upper()} bit {bit}",
            parent_variable_cn=f"{scope_cn}{fp_type.upper()}指纹位{bit}",
            parent_feature_group="molecular_fingerprint",
            mapping_type="fingerprint_bit",
            mechanism_key="fingerprint",
            mapping_note="Fingerprint bit retained separately; map the bit back to a chemical substructure before mechanistic interpretation.",
        )
        return result

    # Main interaction forms.
    m = re.match(r"^Synergy_x_EP_matrix_(LOI|PHRR|THR|Tg|TS(?:_MPa)?)$", base_norm, flags=re.I)
    if m:
        target = _target_display(m.group(1))
        result.update(
            parent_variable=f"Synergy × EP matrix {target}",
            parent_variable_cn=f"协同状态×未改性EP的{target}",
            parent_feature_group="formulation_interaction",
            mapping_type="interaction",
            mechanism_key="synergy_ep_baseline",
            mapping_note="Interaction feature; do not merge with the EP baseline main effect.",
        )
        return result

    m = re.match(r"^P_content_x_EP_matrix_(LOI|PHRR|THR|Tg|TS(?:_MPa)?)$", base_norm, flags=re.I)
    if m:
        target = _target_display(m.group(1))
        result.update(
            parent_variable=f"P content × EP matrix {target}",
            parent_variable_cn=f"磷含量×未改性EP的{target}",
            parent_feature_group="formulation_interaction",
            mapping_type="interaction",
            mechanism_key="p_ep_baseline",
            mapping_note="Interaction feature; represents matrix-dependent phosphorus contribution.",
        )
        return result

    m = re.match(r"^Loading_x_EP_matrix_(LOI|PHRR|THR|Tg|TS(?:_MPa)?)$", base_norm, flags=re.I)
    if m:
        target = _target_display(m.group(1))
        result.update(
            parent_variable=f"FR loading × EP matrix {target}",
            parent_variable_cn=f"阻燃剂添加量×未改性EP的{target}",
            parent_feature_group="formulation_interaction",
            mapping_type="interaction",
            mechanism_key="loading_ep_baseline",
            mapping_note="Interaction feature; represents matrix-dependent loading effect.",
        )
        return result

    m = re.match(r"^P_x_curing_(.+)$", base_norm, flags=re.I)
    if m:
        desc, desc_cn = _descriptor_label(m.group(1))
        result.update(
            parent_variable=f"P content × curing-agent {desc}",
            parent_variable_cn=f"磷含量×固化剂{desc_cn}",
            parent_feature_group="molecular_interaction",
            mapping_type="interaction",
            mechanism_key=f"p_curing_{desc.lower()}",
            mapping_note="Interaction feature coupling phosphorus loading/composition with curing-agent structure.",
        )
        return result

    m = re.match(r"^P_x_CuringAgent_Has_([A-Za-z]+)$", base_norm, flags=re.I)
    if m:
        element = m.group(1).upper()
        result.update(
            parent_variable=f"P content × curing-agent {element} presence",
            parent_variable_cn=f"磷含量×固化剂含{element}",
            parent_feature_group="molecular_interaction",
            mapping_type="interaction",
            mechanism_key="p_curing_element",
            mapping_note="Interaction feature coupling phosphorus with the elemental character of the curing agent.",
        )
        return result

    if re.match(r"^P_loading_x_Synergy$", base_norm, flags=re.I):
        result.update(
            parent_variable="(FR loading × P content) × synergy",
            parent_variable_cn="（阻燃剂添加量×磷含量）×协同状态",
            parent_feature_group="formulation_interaction",
            mapping_type="interaction",
            mechanism_key="p_loading_synergy",
            mapping_note="Legacy-named interaction between total FR loading, formulation-level P content, and synergistic status.",
        )
        return result

    if re.match(r"^Loading_x_Synergy$", base_norm, flags=re.I):
        result.update(
            parent_variable="Total FR loading × synergy",
            parent_variable_cn="总阻燃剂添加量×协同状态",
            parent_feature_group="formulation_interaction",
            mapping_type="interaction",
            mechanism_key="loading_synergy",
            mapping_note="Interaction between total loading and synergistic formulation status.",
        )
        return result

    m = re.match(r"^P_([NBSi]+)_loading_(product|sum|ratio)$", base_norm, flags=re.I)
    if m:
        partner, mode = m.groups()
        partner = partner.replace("SI", "Si").replace("si", "Si")
        result.update(
            parent_variable=f"P–{partner} loading–composition interaction",
            parent_variable_cn=f"P–{partner}添加量–组成交互",
            parent_feature_group="formulation_interaction",
            mapping_type=f"interaction_{mode.lower()}",
            mechanism_key=f"p_{partner.lower()}_loading",
            mapping_note=f"{mode.lower()}-type engineered interaction built from legacy loading×composition features; it is not a direct elemental-loading measurement.",
        )
        return result

    # Baseline property and transforms.
    m = re.match(r"^EP_matrix_(LOI|PHRR|THR|Tg|TS(?:_MPa)?|FS(?:_MPa)?|Char(?:_yield)?)$", base_norm, flags=re.I)
    if m:
        target = m.group(1)
        result.update(
            parent_variable=f"EP matrix {target}",
            parent_variable_cn=f"未改性EP的{target}基线",
            parent_feature_group="ep_baseline",
            mapping_type="base_or_transform",
            mechanism_key="ep_baseline",
            mapping_note="Base and mathematical transforms merged; baseline effect is not a flame-retardant molecular mechanism.",
        )
        return result

    # Core formulation variables.
    exact_map = {
        "Loading_total_FR": ("Total FR loading", "总阻燃剂添加量", "formulation_loading", "fr_loading"),
        "P_content": ("P content", "磷含量", "elemental_composition", "p_content"),
        "N_content": ("N content", "氮含量", "elemental_composition", "n_content"),
        "S_content": ("S content", "硫含量", "elemental_composition", "s_content"),
        "B_content": ("B content", "硼含量", "elemental_composition", "b_content"),
        "Si_content": ("Si content", "硅含量", "elemental_composition", "si_content"),
        "P_loading_real": ("FR loading × P-content interaction", "阻燃剂添加量×磷含量交互", "formulation_interaction", "loading_x_p_content"),
        "N_loading_real": ("FR loading × N-content interaction", "阻燃剂添加量×氮含量交互", "formulation_interaction", "loading_x_n_content"),
        "S_loading_real": ("FR loading × S-content interaction", "阻燃剂添加量×硫含量交互", "formulation_interaction", "loading_x_s_content"),
        "B_loading_real": ("FR loading × B-content interaction", "阻燃剂添加量×硼含量交互", "formulation_interaction", "loading_x_b_content"),
        "Si_loading_real": ("FR loading × Si-content interaction", "阻燃剂添加量×硅含量交互", "formulation_interaction", "loading_x_si_content"),
        "Main_FR_fraction": ("Main FR fraction", "主阻燃剂质量分数", "formulation_loading", "main_fraction"),
        "Co_FR_fraction": ("Co-FR fraction", "协同阻燃剂质量分数", "formulation_loading", "co_fraction"),
        "Cure_Temp_Max": ("Maximum cure temperature", "最高固化温度", "curing_and_preparation", "cure_temperature"),
        "Preparation_Method_num": ("Preparation method", "制备/引入方式", "curing_and_preparation", "preparation_method"),
        "Synergy_flag": ("Synergy flag", "协同体系标记", "formulation_loading", "synergy"),
        "Main_FR_present": ("Main FR presence", "主阻燃剂存在标记", "other", "presence_flag"),
        "Co_FR_present": ("Co-FR presence", "协同阻燃剂存在标记", "other", "presence_flag"),
    }
    if base_norm in exact_map:
        en, cn, group, key = exact_map[base_norm]
        result.update(
            parent_variable=en,
            parent_variable_cn=cn,
            parent_feature_group=group,
            mapping_type="base_or_transform",
            mechanism_key=key,
            mapping_note="Base and mathematical transforms merged into one parent variable.",
        )
        return result

    # Element-presence flags.
    m = re.match(r"^Has_([A-Za-z]+)$", base_norm)
    if m:
        element = m.group(1)
        result.update(
            parent_variable=f"Presence of {element}",
            parent_variable_cn=f"是否含{element}",
            parent_feature_group="elemental_composition",
            mapping_type="binary_flag",
            mechanism_key="element_presence",
            mapping_note="Binary presence flag; interpret together with actual elemental loading.",
        )
        return result

    # One-hot categorical variables.
    if base_norm.startswith("Synergy_type_"):
        category = base_norm.replace("Synergy_type_", "", 1)
        result.update(
            parent_variable="Synergy type",
            parent_variable_cn="协同类型",
            parent_feature_group="curing_and_preparation",
            mapping_type="one_hot_category",
            mechanism_key="synergy_type",
            mapping_note=f"One-hot category '{category}' merged under the Synergy type parent variable.",
        )
        return result

    if base_norm.startswith("Preparation_Method_"):
        category = base_norm.replace("Preparation_Method_", "", 1)
        result.update(
            parent_variable="Preparation method",
            parent_variable_cn="制备/引入方式",
            parent_feature_group="curing_and_preparation",
            mapping_type="one_hot_category",
            mechanism_key="preparation_method",
            mapping_note=f"One-hot category '{category}' merged under Preparation method.",
        )
        return result

    # Molecular descriptors by molecule scope.
    m = re.match(r"^(main|co|curing)_(.+)$", base_norm, flags=re.I)
    if m:
        scope, desc = m.groups()
        scope_en = {"main": "Main FR", "co": "Co-FR", "curing": "Curing agent"}[scope.lower()]
        scope_cn = {"main": "主阻燃剂", "co": "协同阻燃剂", "curing": "固化剂"}[scope.lower()]
        desc_en, desc_cn = _descriptor_label(desc)
        key = f"descriptor_{desc_en.lower()}"
        result.update(
            parent_variable=f"{scope_en} {desc_en}",
            parent_variable_cn=f"{scope_cn}{desc_cn}",
            parent_feature_group="molecular_descriptor",
            mapping_type="molecular_descriptor",
            mechanism_key=key,
            mapping_note="Molecular descriptor retained at scope-specific parent level.",
        )
        return result

    return result


def mechanism_text(key: str, parent_cn: str) -> Tuple[str, str, str, str]:
    """Return physical meaning, cautious interpretation, limitation, literature need."""
    if key == "ep_baseline":
        return (
            "表征未改性环氧基体在相同指标上的初始水平与跨文献基体差异。",
            "基线性能可决定阻燃改性后的绝对性能起点，因此模型可能首先利用基体初始差异，再学习阻燃剂带来的增量。该变量不是阻燃剂分子本身的机理证据。",
            "应避免将其解释为DOPO结构效应；建议同时报告Delta任务或进行基线控制分析。",
            "补充环氧基体组成、固化体系和初始燃烧性能对改性结果影响的文献。",
        )
    if key in {"fr_loading", "main_fraction", "co_fraction"}:
        return (
            "表征阻燃剂总剂量或主/协同组分在配方中的比例。",
            "剂量影响有效阻燃元素浓度、气相抑制、凝聚相成炭及分散状态；过高添加量也可能引起团聚、交联密度下降或力学损失，因此通常具有非线性和最优区间。",
            "平均SHAP方向不能证明单调剂量效应，需结合依赖图和相同体系内的配方梯度。",
            "补充DOPO添加量、协同配比与LOI/PHRR/THR/UL-94变化的剂量效应文献。",
        )
    if key in {"p_content", "p_loading"}:
        return (
            "表征体系中的磷元素组成或按添加量折算的有效磷负载。",
            "磷可通过含磷自由基参与气相自由基抑制，并促进凝聚相脱水、交联和成炭；实际作用取决于P–C/P–N/P–O等化学环境、挥发路径和基体网络。",
            "元素含量不能替代化学结构，且高磷负载不必然带来更优综合性能。",
            "补充DOPO气相自由基抑制、凝聚相促炭及有效磷负载相关文献。",
        )
    if key in {"n_content", "n_loading"}:
        return (
            "表征体系中的氮元素组成或有效氮负载。",
            "氮结构可能促进不可燃气体释放、膨胀成炭或与磷形成协同，但其效果受含氮基团、分解时序和炭层稳定性控制。",
            "N含量增加并不等于稳定P–N协同，某些气体释放过程可能扰动炭层。",
            "补充P–N协同、含氮固化剂及膨胀成炭机理文献。",
        )
    if key == "si_content" or key == "si_loading":
        return (
            "表征硅元素组成或有效硅负载。",
            "硅结构可在凝聚相形成Si–O–Si/SiO2富集层，增强炭层致密性、隔热性和抗氧化能力，并可能与磷促炭过程协同。",
            "P–Si协同依赖分解时序、相容性和炭层连续性，不能仅由Si含量判断。",
            "补充DOPO–Si、POSS或硅氧烷增强炭层的文献。",
        )
    if key.startswith("p_n_loading"):
        return (
            "表征磷与氮有效负载的组合关系。",
            "该组合可反映P–N协同潜力，包括气相稀释/自由基抑制与凝聚相膨胀成炭的共同作用。",
            "工程化和/比值特征只表示统计交互，不证明分子内P–N协同。",
            "补充P–N协同阻燃及不同P/N比例的文献。",
        )
    if key.startswith("p_si_loading"):
        return (
            "表征磷与硅有效负载的组合关系。",
            "磷促进早期成炭，硅有助于形成无机/陶瓷化保护层，两者可能共同提高炭层完整性。",
            "比值或乘积是工程化统计特征，需结合实际P–Si连接方式和残炭表征验证。",
            "补充P–Si协同、Si–O–Si/SiO2保护层及残炭分析文献。",
        )
    if key in {"synergy", "synergy_type", "p_loading_synergy", "loading_synergy", "synergy_ep_baseline"}:
        return (
            "表征是否存在协同组分、协同类型及其与剂量或基体的交互。",
            "协同体系可能通过多相阻燃路径、成炭增强、自由基抑制或屏蔽效应获得高于单一组分的性能，但也可能出现拮抗。",
            "模型中的协同标记是配方类别信息，不能单独证明协同高于线性叠加。",
            "补充协同定义、线性期望比较以及P–N/P–Si/P–B体系文献。",
        )
    if key in {"p_ep_baseline", "loading_ep_baseline"}:
        return (
            "表征阻燃元素或添加量与未改性EP基线性能之间的统计交互。",
            "相同阻燃剂剂量在不同基体与固化网络中可能产生不同增益，说明绝对性能取决于基体起点和改性响应的共同作用。",
            "交互项不能直接说明具体化学反应，需结合基体类别和Delta任务验证。",
            "补充基体依赖性、固化网络差异和阻燃增量分析相关文献。",
        )
    if key == "cure_temperature":
        return (
            "表征体系采用的最高固化温度。",
            "固化温度影响反应完成度、交联密度、相分离和网络缺陷，从而间接改变热分解、燃烧和力学行为。",
            "最高温度不能完整代表升温程序、保温时间和后固化过程。",
            "补充固化制度对环氧交联网络、Tg和阻燃性能影响的文献。",
        )
    if key == "preparation_method":
        return (
            "表征阻燃剂以添加型、反应型、共固化或二次交联方式进入EP网络。",
            "反应型/共固化可降低迁移和团聚并改善网络均匀性，但也可能改变交联密度；添加型效果更依赖分散和界面相容性。",
            "数字编码的SHAP方向不应按大小关系解释，应结合各类别单独比较。",
            "补充添加型与反应型DOPO阻燃剂对迁移、相容性和固化网络影响的文献。",
        )
    if key.startswith("p_curing_") or key == "p_curing_element":
        return (
            "表征磷组成/负载与固化剂分子结构或元素特征的耦合。",
            "固化剂的极性、反应位点、刚性和柔性会改变环氧网络结构，使相同磷负载在不同固化体系中表现出不同的燃烧与热性能。",
            "这是统计交互项，不能直接等同于P与固化剂发生特定化学键合。",
            "补充含磷阻燃剂—固化剂协同、交联密度和网络结构相关文献。",
        )
    if key == "fingerprint":
        return (
            "表征分子中的局部原子环境或子结构片段。",
            "稳定指纹位说明特定局部结构对模型预测有重复贡献，但只有映射回具体子结构后才能讨论DOPO核心、P–N/P–Si连接、芳香片段或反应性官能团。",
            "未完成RDKit位映射前，不得把指纹编号直接写成化学机理。",
            "先完成指纹位—子结构映射，再检索对应结构单元的阻燃或固化机理文献。",
        )
    if key == "presence_flag" or key == "element_presence":
        return (
            "表征某阻燃组分或元素是否存在。",
            "该变量可区分基线样本与含阻燃组分样本，或区分不同元素类别，但信息粒度低于实际含量和分子结构。",
            "存在标记易与Neat EP/添加量共同编码，不应作为独立分子机理。",
            "补充不同元素类别体系的对比文献，并与实际元素负载联合解释。",
        )

    # Descriptor families.
    if "logp" in key:
        return (
            "表征分子疏水性、极性平衡及潜在相容性。",
            "适当的极性匹配可能改善阻燃剂在环氧网络中的分散和界面结合，并影响挥发/迁移倾向。",
            "LogP是整体描述符，不能单独确定相容性或反应性。",
            "补充分子极性、相容性和迁移行为对阻燃性能影响的文献。",
        )
    if "tpsa" in key or "hba" in key or "hbd" in key:
        return (
            "表征分子极性、氢键作用和潜在反应/相互作用位点。",
            "极性与氢键位点可影响环氧/固化剂相容性、固化反应和凝聚相网络结构。",
            "描述符贡献不等于特定官能团已经发生反应，需结合结构和固化化学确认。",
            "补充极性官能团、氢键及反应型DOPO固化行为文献。",
        )
    if "molwt" in key or "heavyatomcount" in key:
        return (
            "表征分子尺寸、原子规模及潜在迁移性。",
            "分子尺寸会影响挥发、扩散、分散和网络嵌入；较大分子可能降低迁移，但也可能带来位阻和相容性问题。",
            "分子量效应常与芳香性、官能度和柔性共线。",
            "补充分子量/大分子阻燃剂迁移、分散和热稳定性文献。",
        )
    if "rotbonds" in key or "fractioncsp3" in key:
        return (
            "表征分子柔性、构象自由度和脂肪化程度。",
            "柔性影响分散、网络运动和裂纹耗能；过高柔性可能降低刚性、Tg或芳香成炭倾向。",
            "其作用可能在阻燃性能与力学/热性能之间存在权衡。",
            "补充刚柔协同、链段运动和芳香成炭相关文献。",
        )
    if "aromaticrings" in key or "ringcount" in key:
        return (
            "表征分子环系与芳香刚性。",
            "芳香结构通常提高刚性和潜在成炭倾向，并可能增强高温残炭骨架，但也可能影响溶解、反应活性和脆性。",
            "环数本身不能区分芳香环类型、连接方式和含杂原子环。",
            "补充芳香结构、刚性和成炭能力相关文献。",
        )
    if "balabanj" in key:
        return (
            "表征分子拓扑连接复杂度。",
            "拓扑复杂度可间接反映支化、环化和连接方式，这些因素可能影响分散、成炭和网络构筑。",
            "拓扑指数缺乏直接机理含义，应与具体分子结构共同解释。",
            "补充支化/超支化DOPO结构与成炭、相容性和力学行为文献。",
        )

    return (
        f"表征父变量“{parent_cn}”对应的配方、结构或测试信息。",
        "该变量在多折模型中具有稳定贡献，说明模型重复利用了该信息；具体材料机理需结合原始结构、依赖图和文献验证。",
        "SHAP仅反映模型依赖关系，不证明因果或单调关系。",
        "根据该变量对应的化学结构或实验条件补充直接文献证据。",
    )


def direction_labels(task: str, positive_fraction: float, consistency: float) -> Tuple[str, str, str]:
    meta = TASK_META.get(task, TASK_META["LOI"])
    if not np.isfinite(positive_fraction) or not np.isfinite(consistency):
        return "Unknown", "方向信息不足", "需补充样本级SHAP"

    if consistency >= 0.8 and positive_fraction >= 0.8:
        output_direction = "Predominantly positive"
        output_cn = meta["positive_output_cn"]
        favorable = meta["objective"] == "max"
    elif consistency >= 0.8 and positive_fraction <= 0.2:
        output_direction = "Predominantly negative"
        output_cn = meta["negative_output_cn"]
        favorable = meta["objective"] == "min"
    else:
        return (
            "Mixed/unstable",
            "不同外层折或子特征的平均SHAP方向不完全一致",
            "不能判断有利/不利；必须结合样本级SHAP依赖图",
        )

    performance_cn = "总体方向与目标优化方向一致" if favorable else "总体方向与目标优化方向相反"
    return output_direction, output_cn, performance_cn


def weighted_average(values: pd.Series, weights: pd.Series) -> float:
    v = pd.to_numeric(values, errors="coerce").to_numpy(dtype=float)
    w = pd.to_numeric(weights, errors="coerce").fillna(0).to_numpy(dtype=float)
    mask = np.isfinite(v) & np.isfinite(w)
    if not mask.any():
        return float("nan")
    if np.sum(w[mask]) <= 0:
        return float(np.nanmean(v[mask]))
    return float(np.average(v[mask], weights=w[mask]))


def find_input_csv(figures_dir: Path, results_root: Path, task: str) -> Path:
    candidates = [
        figures_dir / f"{task}_SHAP_stable_features_filtered.csv",
        results_root / "figures" / f"{task}_SHAP_stable_features_filtered.csv",
    ]
    for p in candidates:
        if p.exists():
            return p
    matches = list(results_root.rglob(f"{task}_SHAP_stability_summary.csv"))
    if len(matches) == 1:
        return matches[0]
    if not matches:
        raise FileNotFoundError(f"No stable SHAP table found for {task} under {results_root}")
    raise RuntimeError(f"Multiple SHAP stability tables found for {task}: {matches}")


def read_task_table(path: Path, task: str, include_levels: Iterable[str]) -> pd.DataFrame:
    df = pd.read_csv(path)
    required = {
        "feature",
        "feature_group",
        "mean_abs_shap_all_folds",
        "selected_feature_frequency",
        "top20_frequency",
        "direction_consistency",
        "positive_direction_fraction_when_selected",
        "folds_present",
        "n_shap_folds",
    }
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"{path} is missing columns: {sorted(missing)}")
    if "stability_level" not in df.columns:
        def infer_level(row: pd.Series) -> str:
            if (
                row.get("folds_present", 0) >= row.get("n_shap_folds", 5)
                and row.get("selected_feature_frequency", 0) >= 0.8
                and row.get("top20_frequency", 0) >= 0.8
                and row.get("direction_consistency", 0) >= 0.8
            ):
                return "High"
            if (
                row.get("folds_present", 0) >= 4
                and row.get("selected_feature_frequency", 0) >= 0.8
                and row.get("top20_frequency", 0) >= 0.6
                and row.get("direction_consistency", 0) >= 0.6
            ):
                return "Medium"
            return "Low"
        df["stability_level"] = df.apply(infer_level, axis=1)

    include = {x.strip() for x in include_levels if x.strip()}
    df = df[df["stability_level"].astype(str).isin(include)].copy()
    df.insert(0, "task", task)
    df["source_csv"] = str(path)
    return df


def build_child_table(task_tables: List[pd.DataFrame]) -> pd.DataFrame:
    child = pd.concat(task_tables, ignore_index=True)
    maps = child.apply(
        lambda r: pd.Series(map_feature_to_parent(str(r["feature"]), str(r["feature_group"]))), axis=1
    )
    for col in maps.columns:
        child[col] = maps[col]
    child["child_importance_rank"] = child.groupby("task")["mean_abs_shap_all_folds"].rank(
        method="dense", ascending=False
    ).astype(int)
    return child


def build_parent_table(child: pd.DataFrame) -> pd.DataFrame:
    rows: List[Dict[str, object]] = []
    group_cols = ["task", "parent_variable", "parent_variable_cn", "parent_feature_group", "mechanism_key"]
    for keys, g in child.groupby(group_cols, dropna=False, sort=False):
        task, parent, parent_cn, parent_group, key = keys
        weights = pd.to_numeric(g["mean_abs_shap_all_folds"], errors="coerce").fillna(0)
        stable_levels = sorted(set(g["stability_level"].astype(str)), key=lambda x: -STABLE_LEVEL_ORDER.get(x, 0))
        parent_level = stable_levels[0] if stable_levels else "Low"
        dominant_idx = pd.to_numeric(g["mean_abs_shap_all_folds"], errors="coerce").idxmax()
        dominant_feature = str(g.loc[dominant_idx, "feature"])
        physical, mechanism, caution, literature = mechanism_text(str(key), str(parent_cn))
        pos_frac = weighted_average(g["positive_direction_fraction_when_selected"], weights)
        dir_cons = weighted_average(g["direction_consistency"], weights)
        direction_en, direction_cn, performance_cn = direction_labels(str(task), pos_frac, dir_cons)
        rows.append(
            {
                "task": task,
                "target_cn": TASK_META.get(str(task), {}).get("target_cn", str(task)),
                "parent_variable": parent,
                "parent_variable_cn": parent_cn,
                "parent_feature_group": parent_group,
                "mechanism_key": key,
                "parent_stability_level": parent_level,
                "child_feature_count": int(len(g)),
                "child_features": "; ".join(g.sort_values("mean_abs_shap_all_folds", ascending=False)["feature"].astype(str)),
                "dominant_child_feature": dominant_feature,
                "parent_importance_sum": float(weights.sum()),
                "parent_importance_max_child": float(weights.max()),
                "parent_importance_mean_child": float(weights.mean()),
                "selected_feature_frequency_weighted": weighted_average(g["selected_feature_frequency"], weights),
                "top20_frequency_weighted": weighted_average(g["top20_frequency"], weights),
                "direction_consistency_weighted": dir_cons,
                "positive_direction_fraction_weighted": pos_frac,
                "folds_present_max": int(pd.to_numeric(g["folds_present"], errors="coerce").max()),
                "n_shap_folds_max": int(pd.to_numeric(g["n_shap_folds"], errors="coerce").max()),
                "average_output_direction": direction_en,
                "average_output_direction_cn": direction_cn,
                "performance_direction_cn": performance_cn,
                "physical_meaning_cn": physical,
                "mechanism_interpretation_cn": mechanism,
                "writing_caution_cn": caution,
                "literature_support_needed_cn": literature,
                "aggregation_caution": "Correlated transforms can split SHAP attribution. Use max-child importance for conservative ranking; sum is bookkeeping only.",
            }
        )
    parent = pd.DataFrame(rows)
    parent["parent_importance_share_of_stable_sum"] = parent.groupby("task")["parent_importance_sum"].transform(
        lambda x: x / x.sum() if x.sum() else np.nan
    )
    parent["parent_rank_conservative"] = parent.groupby("task")["parent_importance_max_child"].rank(
        method="dense", ascending=False
    ).astype(int)
    parent["parent_rank_sum"] = parent.groupby("task")["parent_importance_sum"].rank(
        method="dense", ascending=False
    ).astype(int)
    return parent.sort_values(["task", "parent_rank_conservative", "parent_rank_sum", "parent_variable"])


def plot_parent_top(parent_task: pd.DataFrame, task: str, out_dir: Path, top_n: int) -> Tuple[Path, Path]:
    plot_df = parent_task.sort_values(
        ["parent_importance_max_child", "parent_importance_sum"], ascending=False
    ).head(top_n).copy()
    plot_df = plot_df.sort_values("parent_importance_max_child", ascending=True)
    labels = plot_df["parent_variable"].astype(str)
    values = plot_df["parent_importance_max_child"].astype(float)

    height = max(5.5, 0.48 * len(plot_df) + 1.8)
    fig, ax = plt.subplots(figsize=(10.5, height))
    ax.barh(labels, values)
    ax.set_xlabel("Conservative parent importance (max child mean |SHAP|)")
    ax.set_ylabel("")
    ax.set_title(f"{task}: stable SHAP parent variables")
    ax.grid(axis="x", alpha=0.25)
    for idx, (_, row) in enumerate(plot_df.iterrows()):
        ax.text(
            float(row["parent_importance_max_child"]),
            idx,
            f"  n={int(row['child_feature_count'])}; {row['parent_stability_level']}",
            va="center",
            fontsize=8.5,
        )
    fig.tight_layout()
    png = out_dir / f"{task}_SHAP_parent_top{top_n}.png"
    pdf = out_dir / f"{task}_SHAP_parent_top{top_n}.pdf"
    fig.savefig(png, dpi=600, bbox_inches="tight")
    fig.savefig(pdf, bbox_inches="tight")
    plt.close(fig)
    return png, pdf


def write_markdown_summary(
    parent: pd.DataFrame,
    output_path: Path,
    top_n: int,
    tasks: Iterable[str] | None = None,
    title: str = "核心任务SHAP稳定父变量汇总",
) -> None:
    lines: List[str] = []
    lines.append(f"# {title}")
    lines.append("")
    lines.append("> 说明：父变量按其最重要子特征的mean |SHAP|进行保守排序。SHAP反映模型依赖关系，不代表因果关系；数学变换项的贡献可能因共线性被拆分。")
    lines.append("")
    task_order = list(tasks) if tasks is not None else list(dict.fromkeys(parent["task"].astype(str)))
    for task in task_order:
        g = parent[parent["task"] == task].sort_values("parent_rank_conservative").head(top_n)
        if g.empty:
            continue
        lines.append(f"## {task}")
        lines.append("")
        lines.append("| 排名 | 父变量 | 稳定级别 | 保守重要性 | 子特征数 | 平均方向 | 论文解释重点 |")
        lines.append("|---:|---|---|---:|---:|---|---|")
        for _, r in g.iterrows():
            mechanism = str(r["mechanism_interpretation_cn"]).replace("|", "；")
            if len(mechanism) > 88:
                mechanism = mechanism[:88] + "……"
            lines.append(
                f"| {int(r['parent_rank_conservative'])} | {r['parent_variable_cn']} | {r['parent_stability_level']} | "
                f"{float(r['parent_importance_max_child']):.6g} | {int(r['child_feature_count'])} | "
                f"{r['average_output_direction_cn']} | {mechanism} |"
            )
        lines.append("")
        lines.append("**写作提醒：** 只有方向一致性较高且正/负方向占比明确时，才能描述为“总体偏正/偏负”；判断单调关系仍需样本级SHAP依赖图。")
        lines.append("")
    output_path.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Merge stable SHAP child features into parent variables.")
    parser.add_argument("--results-root", default="results/05_Shap/FINAL_core_fixed_baseline_inclusive_5x5", help="Root containing core SHAP task results.")
    parser.add_argument("--figures-dir", default="results/05_Shap/FINAL_core_fixed_baseline_inclusive_5x5/figures", help="Folder with *_stable_features_filtered.csv files.")
    parser.add_argument("--output-dir", default="results/05_Shap/core_features", help="Canonical output folder.")
    parser.add_argument("--tasks", default=",".join(DEFAULT_TASKS), help="Comma-separated tasks.")
    parser.add_argument("--include-levels", default="High,Medium", help="Stability levels to aggregate.")
    parser.add_argument("--top-parent-n", type=int, default=12, help="Parent variables shown in each plot/summary.")
    parser.add_argument(
        "--output-prefix",
        default="core",
        help="Prefix used for combined table filenames. Default keeps STEP2 core filenames.",
    )
    parser.add_argument(
        "--step-label",
        default="STEP2",
        help="Label used in summary, manifest and run-config filenames.",
    )
    parser.add_argument(
        "--summary-title",
        default="核心任务SHAP稳定父变量汇总",
        help="Chinese markdown summary title.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    tasks = [x.strip() for x in args.tasks.split(",") if x.strip()]
    levels = [x.strip() for x in args.include_levels.split(",") if x.strip()]
    results_root = Path(args.results_root).resolve()
    figures_dir = Path(args.figures_dir).resolve()
    output_dir = Path(args.output_dir).resolve()
    tables_dir = output_dir / "tables"
    figures_out = output_dir / "figures"
    tables_dir.mkdir(parents=True, exist_ok=True)
    figures_out.mkdir(parents=True, exist_ok=True)

    task_tables: List[pd.DataFrame] = []
    manifest_rows: List[Dict[str, object]] = []
    for task in tasks:
        print("=" * 88)
        print(f"[STEP2] task={task}")
        source = find_input_csv(figures_dir, results_root, task)
        df = read_task_table(source, task, levels)
        task_tables.append(df)
        manifest_rows.append({"task": task, "source_csv": str(source), "stable_child_features": len(df)})
        print(f"[OK] {task}: source={source}; selected stable child features={len(df)}")

    child = build_child_table(task_tables)
    parent = build_parent_table(child)

    prefix = str(args.output_prefix).strip() or "core"
    step_label = str(args.step_label).strip() or "STEP2"
    child_path = tables_dir / f"{prefix}_stable_child_features_with_parent_mapping.csv"
    parent_path = tables_dir / f"{prefix}_stable_parent_variables.csv"
    mechanism_path = tables_dir / f"{prefix}_parent_variable_mechanism_template.csv"
    audit_path = tables_dir / f"{prefix}_parent_feature_mapping_audit.csv"

    child.to_csv(child_path, index=False, encoding="utf-8-sig")
    parent.to_csv(parent_path, index=False, encoding="utf-8-sig")
    parent[[
        "task", "parent_rank_conservative", "parent_variable", "parent_variable_cn",
        "parent_feature_group", "parent_stability_level", "average_output_direction_cn",
        "performance_direction_cn", "physical_meaning_cn", "mechanism_interpretation_cn",
        "writing_caution_cn", "literature_support_needed_cn", "child_features"
    ]].to_csv(mechanism_path, index=False, encoding="utf-8-sig")
    child[[
        "task", "feature", "feature_group", "stability_level", "parent_variable",
        "parent_variable_cn", "parent_feature_group", "mapping_type", "transform_tags",
        "mechanism_key", "mapping_note"
    ]].to_csv(audit_path, index=False, encoding="utf-8-sig")

    plot_manifest: List[Dict[str, object]] = []
    for task in tasks:
        g = parent[parent["task"] == task].copy()
        task_table = tables_dir / f"{task}_stable_parent_variables.csv"
        g.to_csv(task_table, index=False, encoding="utf-8-sig")
        png, pdf = plot_parent_top(g, task, figures_out, args.top_parent_n)
        plot_manifest.append({
            "task": task,
            "parent_variables": len(g),
            "top_plot_png": str(png),
            "top_plot_pdf": str(pdf),
            "task_table": str(task_table),
        })
        print(f"[OK] {task}: parent variables={len(g)}; plot={png.name}")

    summary_path = output_dir / f"{step_label}_{prefix}_parent_variable_summary.md"
    write_markdown_summary(
        parent, summary_path, args.top_parent_n, tasks=tasks, title=args.summary_title
    )

    manifest = pd.DataFrame(manifest_rows).merge(pd.DataFrame(plot_manifest), on="task", how="left")
    manifest_path = output_dir / f"{step_label}_manifest.csv"
    manifest.to_csv(manifest_path, index=False, encoding="utf-8-sig")

    config = {
        "tasks": tasks,
        "include_levels": levels,
        "ranking_rule": "parent_importance_max_child descending (conservative)",
        "sum_importance_note": "parent_importance_sum is bookkeeping because correlated transforms can split SHAP attribution",
        "direction_note": "average SHAP-output direction only; not proof of monotonicity or causality",
        "top_parent_n": args.top_parent_n,
        "output_prefix": prefix,
        "step_label": step_label,
        "summary_title": args.summary_title,
        "results_root": str(results_root),
        "figures_dir": str(figures_dir),
        "output_dir": str(output_dir),
    }
    (output_dir / f"{step_label}_run_config.json").write_text(json.dumps(config, ensure_ascii=False, indent=2), encoding="utf-8")

    print("\n[DONE] Parent table:", parent_path)
    print("[DONE] Mechanism template:", mechanism_path)
    print("[DONE] Summary:", summary_path)
    print("[DONE] Manifest:", manifest_path)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"[ERROR] {type(exc).__name__}: {exc}", file=sys.stderr)
        raise
