# -*- coding: utf-8 -*-
"""Create publication-ready SHAP stability figures from existing nested-CV CSV files.

This script does not retrain models and does not recalculate SHAP values. It reads the
CSV files already generated by ``run_scientific_evaluation.py --shap-stability``.

Outputs per task
----------------
1. Stable Top-N feature importance bar chart.
2. Feature-group contribution bar chart.
3. Outer-fold SHAP rank Spearman heatmap.
4. Filtered stable-feature CSV.

The script searches recursively below ``--results`` so it works with the current
layout, for example::

    results/05_Shap/FINAL_core_fixed_baseline_inclusive_5x5/PHRR/molecule/formulation/without_BDE/

Example::

    python 05_Shap/plot_shap_stability.py \
        --results results/05_Shap \
        --tasks LOI,PHRR,THR,UL94_V0 \
        --top-n 15
"""
from __future__ import annotations

import argparse
import math
import re
import sys
from pathlib import Path
from typing import Iterable

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


TASK_DISPLAY = {
    "LOI": "LOI",
    "PHRR": "PHRR",
    "THR": "THR",
    "UL94": "UL-94 V-0",
    "UL94_V0": "UL-94 V-0",
    "Tg": "Tg",
    "TS": "Tensile strength",
    "TS_MPa": "Tensile strength",
    "FS": "Flexural strength",
    "FS_MPa": "Flexural strength",
}

GROUP_DISPLAY = {
    "ep_baseline": "EP baseline property",
    "formulation_loading": "Formulation and loading",
    "elemental_composition": "Elemental composition",
    "molecular_descriptor": "Molecular descriptors",
    "molecular_fingerprint": "Molecular fingerprints",
    "curing_and_preparation": "Curing and preparation",
    "test_condition": "Test conditions",
    "other": "Other features",
}

REQUIRED_STABILITY_COLUMNS = {
    "feature",
    "feature_group",
    "mean_abs_shap_all_folds",
    "selected_feature_frequency",
    "top20_frequency",
    "direction_consistency",
    "folds_present",
    "n_shap_folds",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--results",
        type=Path,
        required=True,
        help="Root directory containing SHAP stability CSV files. Searched recursively.",
    )
    parser.add_argument(
        "--tasks",
        default="LOI,PHRR,THR,UL94_V0",
        help="Comma-separated task names. Use ALL to plot every discovered task.",
    )
    parser.add_argument("--top-n", type=int, default=15, help="Maximum features in Top-N plot.")
    parser.add_argument("--min-folds", type=int, default=4)
    parser.add_argument("--min-selected-frequency", type=float, default=0.80)
    parser.add_argument("--min-top20-frequency", type=float, default=0.60)
    parser.add_argument("--min-direction-consistency", type=float, default=0.60)
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Figure output directory. Default: <results>/figures",
    )
    parser.add_argument("--dpi", type=int, default=600)
    parser.add_argument(
        "--formats",
        default="png,pdf",
        help="Comma-separated output formats, e.g. png,pdf or png,svg.",
    )
    parser.add_argument(
        "--include-low-stability-fill",
        action="store_true",
        help=(
            "If fewer than Top-N features pass the stability thresholds, fill the plot "
            "with the highest remaining features. Filled rows remain marked Low."
        ),
    )
    return parser.parse_args()


def configure_matplotlib() -> None:
    plt.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": [
                "Arial",
                "DejaVu Sans",
                "Microsoft YaHei",
                "SimHei",
            ],
            "axes.unicode_minus": False,
            "font.size": 10,
            "axes.titlesize": 12,
            "axes.labelsize": 10,
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )


def task_from_stability_file(path: Path) -> str:
    suffix = "_SHAP_stability_summary.csv"
    if not path.name.endswith(suffix):
        raise ValueError(f"Not a SHAP stability summary: {path}")
    return path.name[: -len(suffix)]


def normalize_task(task: str) -> str:
    text = task.strip()
    aliases = {
        "UL94": "UL94_V0",
        "UL-94": "UL94_V0",
        "TS": "TS_MPa",
        "FS": "FS_MPa",
    }
    return aliases.get(text, text)


def discover_task_files(results_root: Path) -> dict[str, Path]:
    discovered: dict[str, Path] = {}
    for path in sorted(results_root.rglob("*_SHAP_stability_summary.csv")):
        task = normalize_task(task_from_stability_file(path))
        # Prefer the shortest path if accidental duplicate copies exist.
        old = discovered.get(task)
        if old is None or len(path.parts) < len(old.parts):
            discovered[task] = path
    return discovered


def sibling_file(stability_path: Path, task: str, suffix: str) -> Path:
    return stability_path.with_name(f"{task}{suffix}")


def validate_stability_frame(df: pd.DataFrame, path: Path) -> None:
    missing = sorted(REQUIRED_STABILITY_COLUMNS - set(df.columns))
    if missing:
        raise ValueError(f"{path} is missing columns: {missing}")


def classify_stability(df: pd.DataFrame, args: argparse.Namespace) -> pd.Series:
    n_folds = pd.to_numeric(df["n_shap_folds"], errors="coerce")
    folds = pd.to_numeric(df["folds_present"], errors="coerce")
    top20 = pd.to_numeric(df["top20_frequency"], errors="coerce")
    direction = pd.to_numeric(df["direction_consistency"], errors="coerce")
    selected = pd.to_numeric(df["selected_feature_frequency"], errors="coerce")

    high = (
        (folds >= n_folds.fillna(5))
        & (top20 >= 0.80)
        & (direction >= 0.80)
        & (selected >= 0.80)
    )
    medium = (
        (folds >= args.min_folds)
        & (top20 >= args.min_top20_frequency)
        & (direction >= args.min_direction_consistency)
        & (selected >= args.min_selected_frequency)
    )
    return pd.Series(np.where(high, "High", np.where(medium, "Medium", "Low")), index=df.index)


def safe_float(value: object, default: float = float("nan")) -> float:
    try:
        number = float(value)
        return number if math.isfinite(number) else default
    except (TypeError, ValueError):
        return default


def shorten_feature_label(text: object, max_length: int = 48) -> str:
    label = str(text)
    label = label.replace(" wt%", " (wt%)")
    if len(label) <= max_length:
        return label
    return label[: max_length - 1] + "…"


def save_figure(fig: plt.Figure, stem: Path, formats: Iterable[str], dpi: int) -> list[Path]:
    saved: list[Path] = []
    for fmt in formats:
        fmt = fmt.strip().lower().lstrip(".")
        if not fmt:
            continue
        output = stem.with_suffix(f".{fmt}")
        kwargs = {"bbox_inches": "tight"}
        if fmt == "png":
            kwargs["dpi"] = dpi
        fig.savefig(output, **kwargs)
        saved.append(output)
    plt.close(fig)
    return saved


def plot_top_features(
    task: str,
    stable_df: pd.DataFrame,
    output_dir: Path,
    args: argparse.Namespace,
    formats: list[str],
) -> list[Path]:
    selected = stable_df.loc[stable_df["stability_level"].isin(["High", "Medium"])].copy()
    selected = selected.sort_values("mean_abs_shap_all_folds", ascending=False)

    if args.include_low_stability_fill and len(selected) < args.top_n:
        remaining = stable_df.loc[~stable_df.index.isin(selected.index)].copy()
        remaining = remaining.sort_values("mean_abs_shap_all_folds", ascending=False)
        selected = pd.concat([selected, remaining.head(args.top_n - len(selected))], ignore_index=False)

    selected = selected.head(args.top_n).sort_values("mean_abs_shap_all_folds", ascending=True)
    if selected.empty:
        raise ValueError(
            f"{task}: no features passed the stability thresholds. "
            "Use --include-low-stability-fill or relax thresholds."
        )

    height = max(4.8, 0.42 * len(selected) + 1.7)
    fig, ax = plt.subplots(figsize=(8.6, height))
    y = np.arange(len(selected))
    values = selected["mean_abs_shap_all_folds"].astype(float).to_numpy()
    ax.barh(y, values)
    ax.set_yticks(y)
    ax.set_yticklabels([shorten_feature_label(x) for x in selected["feature"]])
    ax.set_xlabel("Mean |SHAP value| across outer folds")
    ax.set_title(f"{TASK_DISPLAY.get(task, task)}: stable SHAP features")
    ax.grid(axis="x", alpha=0.25)

    max_value = max(float(np.nanmax(values)), 1e-12)
    for idx, (_, row) in enumerate(selected.iterrows()):
        top20 = safe_float(row.get("top20_frequency"), 0.0)
        direction = safe_float(row.get("direction_consistency"), 0.0)
        level = row.get("stability_level", "")
        annotation = f"Top20={top20:.1f}; Dir={direction:.1f}; {level}"
        ax.text(values[idx] + max_value * 0.012, idx, annotation, va="center", fontsize=8)
    ax.set_xlim(0, max_value * 1.48)

    stem = output_dir / f"{task}_SHAP_top{min(args.top_n, len(selected))}_stable_features"
    return save_figure(fig, stem, formats, args.dpi)


def plot_group_contribution(
    task: str,
    group_path: Path,
    output_dir: Path,
    args: argparse.Namespace,
    formats: list[str],
) -> list[Path]:
    if not group_path.exists():
        raise FileNotFoundError(f"Missing group summary: {group_path}")
    df = pd.read_csv(group_path)
    required = {"feature_group", "mean_abs_shap_all_folds_sum"}
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"{group_path} is missing columns: {missing}")

    df = df.copy()
    df["contribution"] = pd.to_numeric(df["mean_abs_shap_all_folds_sum"], errors="coerce").fillna(0.0)
    total = float(df["contribution"].sum())
    df["contribution_percent"] = 100.0 * df["contribution"] / total if total > 0 else 0.0
    df["group_label"] = df["feature_group"].map(GROUP_DISPLAY).fillna(df["feature_group"])
    df = df.sort_values("contribution_percent", ascending=True)

    fig, ax = plt.subplots(figsize=(8.2, max(4.6, 0.5 * len(df) + 1.6)))
    y = np.arange(len(df))
    values = df["contribution_percent"].to_numpy()
    ax.barh(y, values)
    ax.set_yticks(y)
    ax.set_yticklabels(df["group_label"])
    ax.set_xlabel("Share of total mean |SHAP| (%)")
    ax.set_title(f"{TASK_DISPLAY.get(task, task)}: SHAP contribution by feature group")
    ax.grid(axis="x", alpha=0.25)
    max_value = max(float(np.nanmax(values)), 1.0)
    for idx, value in enumerate(values):
        ax.text(value + max_value * 0.015, idx, f"{value:.1f}%", va="center", fontsize=8)
    ax.set_xlim(0, max_value * 1.18)

    csv_out = output_dir / f"{task}_SHAP_group_contribution_percent.csv"
    df[["feature_group", "group_label", "contribution", "contribution_percent"]].to_csv(
        csv_out, index=False, encoding="utf-8-sig"
    )
    stem = output_dir / f"{task}_SHAP_group_contribution"
    return save_figure(fig, stem, formats, args.dpi)


def plot_rank_heatmap(
    task: str,
    rank_path: Path,
    output_dir: Path,
    args: argparse.Namespace,
    formats: list[str],
) -> tuple[list[Path], float]:
    if not rank_path.exists():
        raise FileNotFoundError(f"Missing rank Spearman file: {rank_path}")
    raw = pd.read_csv(rank_path)
    if raw.shape[1] < 2:
        raise ValueError(f"Invalid rank Spearman matrix: {rank_path}")

    index_col = raw.columns[0]
    labels = raw[index_col].astype(str).tolist()
    matrix = raw.drop(columns=[index_col]).apply(pd.to_numeric, errors="coerce")
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError(f"Rank Spearman matrix is not square: {rank_path}")
    values = matrix.to_numpy(dtype=float)

    mask = ~np.eye(values.shape[0], dtype=bool)
    mean_off_diagonal = float(np.nanmean(values[mask])) if mask.any() else float("nan")

    fig, ax = plt.subplots(figsize=(6.2, 5.2))
    image = ax.imshow(values, vmin=-1.0, vmax=1.0, cmap="coolwarm")
    ax.set_xticks(np.arange(len(labels)))
    ax.set_yticks(np.arange(len(labels)))
    ax.set_xticklabels([f"Fold {x}" for x in labels])
    ax.set_yticklabels([f"Fold {x}" for x in labels])
    ax.set_title(
        f"{TASK_DISPLAY.get(task, task)}: SHAP rank Spearman correlation\n"
        f"Mean off-diagonal r = {mean_off_diagonal:.3f}"
    )
    for i in range(values.shape[0]):
        for j in range(values.shape[1]):
            value = values[i, j]
            if math.isfinite(value):
                ax.text(j, i, f"{value:.2f}", ha="center", va="center", fontsize=8)
    colorbar = fig.colorbar(image, ax=ax, fraction=0.046, pad=0.04)
    colorbar.set_label("Spearman r")

    stem = output_dir / f"{task}_SHAP_rank_spearman_heatmap"
    return save_figure(fig, stem, formats, args.dpi), mean_off_diagonal


def process_task(
    task: str,
    stability_path: Path,
    output_dir: Path,
    args: argparse.Namespace,
    formats: list[str],
) -> dict[str, object]:
    df = pd.read_csv(stability_path)
    validate_stability_frame(df, stability_path)
    df = df.copy()
    numeric_columns = [
        "mean_abs_shap_all_folds",
        "selected_feature_frequency",
        "top20_frequency",
        "direction_consistency",
        "positive_direction_fraction_when_selected",
        "mean_signed_shap_all_folds",
        "folds_present",
        "n_shap_folds",
    ]
    for column in numeric_columns:
        if column in df.columns:
            df[column] = pd.to_numeric(df[column], errors="coerce")
    df["stability_level"] = classify_stability(df, args)
    df = df.sort_values("mean_abs_shap_all_folds", ascending=False)

    stable_csv = output_dir / f"{task}_SHAP_stable_features_filtered.csv"
    df.to_csv(stable_csv, index=False, encoding="utf-8-sig")

    group_path = sibling_file(stability_path, task, "_SHAP_group_summary.csv")
    rank_path = sibling_file(stability_path, task, "_SHAP_rank_spearman.csv")

    saved = []
    saved.extend(plot_top_features(task, df, output_dir, args, formats))
    saved.extend(plot_group_contribution(task, group_path, output_dir, args, formats))
    heatmap_files, mean_spearman = plot_rank_heatmap(task, rank_path, output_dir, args, formats)
    saved.extend(heatmap_files)

    high_count = int((df["stability_level"] == "High").sum())
    medium_count = int((df["stability_level"] == "Medium").sum())
    low_count = int((df["stability_level"] == "Low").sum())
    return {
        "task": task,
        "stability_summary": str(stability_path),
        "stable_feature_csv": str(stable_csv),
        "high_stability_features": high_count,
        "medium_stability_features": medium_count,
        "low_stability_features": low_count,
        "mean_rank_spearman_off_diagonal": mean_spearman,
        "figure_files": " | ".join(str(path) for path in saved),
    }


def main() -> None:
    args = parse_args()
    configure_matplotlib()

    results_root = args.results.resolve()
    if not results_root.exists():
        raise FileNotFoundError(f"Results directory does not exist: {results_root}")
    output_dir = (args.output or (results_root / "figures")).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    formats = [part.strip().lower() for part in args.formats.split(",") if part.strip()]
    if not formats:
        raise ValueError("At least one output format is required.")

    discovered = discover_task_files(results_root)
    if not discovered:
        raise FileNotFoundError(
            f"No *_SHAP_stability_summary.csv files were found below: {results_root}"
        )

    requested_raw = [x.strip() for x in args.tasks.split(",") if x.strip()]
    if len(requested_raw) == 1 and requested_raw[0].upper() == "ALL":
        requested = sorted(discovered)
    else:
        requested = [normalize_task(x) for x in requested_raw]

    missing_tasks = [task for task in requested if task not in discovered]
    if missing_tasks:
        available = ", ".join(sorted(discovered))
        raise FileNotFoundError(
            f"Missing SHAP stability results for: {missing_tasks}. Discovered tasks: {available}"
        )

    manifest_rows = []
    failures = []
    for task in requested:
        print("=" * 88)
        print(f"[PLOT SHAP] task={task}")
        try:
            row = process_task(task, discovered[task], output_dir, args, formats)
            manifest_rows.append(row)
            print(
                f"[OK] {task}: high={row['high_stability_features']}, "
                f"medium={row['medium_stability_features']}, "
                f"mean_rank_spearman={row['mean_rank_spearman_off_diagonal']:.3f}"
            )
        except Exception as exc:  # continue to report all task failures
            failures.append((task, str(exc)))
            print(f"[FAIL] {task}: {exc}", file=sys.stderr)

    manifest = pd.DataFrame(manifest_rows)
    manifest_path = output_dir / "SHAP_figure_manifest.csv"
    manifest.to_csv(manifest_path, index=False, encoding="utf-8-sig")
    print(f"\n[DONE] Manifest: {manifest_path}")
    print(f"[DONE] Figures: {output_dir}")

    if failures:
        detail = "; ".join(f"{task}: {message}" for task, message in failures)
        raise RuntimeError(f"One or more tasks failed: {detail}")


if __name__ == "__main__":
    main()
