# -*- coding: utf-8 -*-
"""Generate five compact, deduplicated main-text tables for the manuscript.

This script consumes the database and the raw paper-table outputs generated by
``run.py paper-tables``. It does not retrain any model and never selects a best
fold. Only the frozen five-outer-fold molecule-grouped results are retained for
Table 3.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(Path(__file__).resolve().parent) not in sys.path:
    sys.path.insert(0, str(Path(__file__).resolve().parent))

from paper_utils import (  # noqa: E402
    TARGET_COLUMNS,
    canonical_smiles,
    murcko_scaffold,
    normalise_ul94,
    numeric,
    read_csv_auto,
    task_label,
)

MAIN_TASKS = ["LOI", "PHRR", "THR", "UL94_V0", "Tg", "TS_MPa"]
CORE_ROBUSTNESS_TASKS = ["LOI", "PHRR", "THR", "UL94_V0"]

# Verified literature-reference counts from the finalized source record.
# The 98-column modeling CSV intentionally contains no bibliographic field,
# so these counts are used as a documented fallback for Main-text Table 1.
FINAL_REFERENCE_COUNTS = {
    "LOI": 130,
    "PHRR": 116,
    "THR": 113,
    "UL94_V0": 130,
    "Tg": 90,
    "TS_MPa": 66,
}


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--data", type=Path, default=ROOT / "data" / "DOPO_EP_new_with_BDE.csv")
    p.add_argument("--tables-root", type=Path, default=ROOT / "results" / "09_PaperTables")
    p.add_argument("--task-config", type=Path, default=ROOT / "config" / "task_config.json")
    p.add_argument("--output", type=Path, default=ROOT / "results" / "09_MainTextTables")
    return p.parse_args()


def _fmt(mean: object, std: object, digits: int = 3) -> str:
    m = pd.to_numeric(pd.Series([mean]), errors="coerce").iloc[0]
    s = pd.to_numeric(pd.Series([std]), errors="coerce").iloc[0]
    if pd.isna(m):
        return ""
    if pd.isna(s):
        return f"{m:.{digits}f}"
    return f"{m:.{digits}f} ± {s:.{digits}f}"


def _task_target_summary(task: str, series: pd.Series) -> tuple[str, str]:
    if task == "UL94_V0":
        y = normalise_ul94(series).dropna().astype(int)
        counts = y.value_counts().to_dict()
        return "Binary classification", f"V-0={counts.get(1, 0)}; non-V-0={counts.get(0, 0)}"
    values = numeric(series).dropna()
    if values.empty:
        return "Regression", ""
    return "Regression", f"{values.min():.2f}–{values.max():.2f}; median={values.median():.2f}"


def table1_dataset_overview(df: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, object]] = []
    ref_col = next((c for c in ["Reference", "DOI", "Reference_ID", "Source"] if c in df.columns), None)
    for task in MAIN_TASKS:
        target_col = TARGET_COLUMNS[task]
        if target_col not in df.columns:
            continue
        valid = df[target_col].notna()
        sub = df.loc[valid].copy()
        main = sub.get("SMILES_main", pd.Series(index=sub.index, dtype=object)).map(canonical_smiles)
        co = sub.get("SMILES_co", pd.Series(index=sub.index, dtype=object)).map(canonical_smiles).fillna("NONE")
        pairs = (main.fillna("INVALID") + "||" + co).nunique()
        scaffolds = main.dropna().map(murcko_scaffold).dropna().nunique()
        task_type, target_summary = _task_target_summary(task, sub[target_col])
        rows.append({
            "Task": task_label(task).replace("$", ""),
            "Task type": task_type,
            "Valid records (n)": int(valid.sum()),
            "Unique main FRs": int(main.dropna().nunique()),
            "Unique main/co pairs": int(pairs),
            "Unique main scaffolds": int(scaffolds),
            "References (n)": (
                int(sub[ref_col].nunique(dropna=True))
                if ref_col
                else FINAL_REFERENCE_COUNTS.get(task, np.nan)
            ),
            "Target range / class balance": target_summary,
        })
    return pd.DataFrame(rows)


def table2_frozen_config(tables_root: Path, config_path: Path) -> pd.DataFrame:
    source = tables_root / "TableS2A_frozen_task_configurations.csv"
    if not source.exists():
        source = tables_root / "TableS2_frozen_task_configurations.csv"
    if source.exists():
        cfg = read_csv_auto(source)
    else:
        payload = json.loads(config_path.read_text(encoding="utf-8"))
        rows = []
        for task, item in payload.get("tasks", {}).items():
            rows.append({"task": task, "valid_target_n": np.nan, "task_type": item.get("type"),
                         "frozen_view": item.get("view"), "frozen_k": item.get("k"),
                         "group_rule": item.get("group"), "main_with_BDE": item.get("main_bde")})
        cfg = pd.DataFrame(rows)
    cfg = cfg[cfg["task"].isin(MAIN_TASKS)].copy()
    cfg["_order"] = cfg["task"].map({t: i for i, t in enumerate(MAIN_TASKS)})
    cfg = cfg.sort_values("_order")
    out = pd.DataFrame({
        "Task": cfg["task"].map(lambda x: task_label(x).replace("$", "")),
        "Valid records (n)": cfg.get("valid_target_n", np.nan),
        "Task type": cfg.get("task_type", ""),
        "Frozen feature view": cfg.get("frozen_view", ""),
        "Frozen K": cfg.get("frozen_k", "").replace({np.nan: "ALL", "all": "ALL", "All": "ALL"}),
        "Grouping rule": cfg.get("group_rule", ""),
        "Main model uses BDE": cfg.get("main_with_BDE", False),
        "Primary metric": cfg["task"].map(lambda x: "Macro-F1" if x == "UL94_V0" else "R²"),
    })
    return out.reset_index(drop=True)


def _preferred_summary_row(all_metrics: pd.DataFrame, task: str) -> pd.Series | None:
    g = all_metrics.copy()
    g = g[g["task"].astype(str).eq(task)]
    if "use_BDE" in g:
        g = g[pd.to_numeric(g["use_BDE"], errors="coerce").fillna(0).eq(0)]
    if "split_strategy" in g:
        g = g[g["split_strategy"].astype(str).str.lower().eq("molecule")]
    if "screening_mode" in g:
        g = g[g["screening_mode"].astype(str).str.lower().eq("formulation")]
    if "selection_scope" in g:
        g = g[g["selection_scope"].astype(str).str.lower().eq("fixed")]
    if g.empty:
        return None
    source = g.get("source_file", pd.Series("", index=g.index)).astype(str).str.lower()
    desired = "final_aux_fixed_baseline_inclusive_5x5" if task in {"Tg", "TS_MPa"} else "final_core_fixed_baseline_inclusive_5x5"
    score = np.zeros(len(g), dtype=float)
    score += source.str.contains(desired, regex=False).to_numpy() * 100
    score += source.str.endswith(f"/{task.lower()}_nested_summary.csv").to_numpy() * 20
    score += (~source.str.contains("scientific_nested_summary_all", regex=False)).to_numpy() * 5
    score -= source.str.contains("smoke|conditions_only|molecular_only", regex=True).to_numpy() * 100
    g = g.assign(_priority=score)
    g = g.sort_values("_priority", ascending=False)
    metric_cols = [c for c in ["outer_R2_mean", "outer_Macro_F1_mean", "outer_RMSE_mean", "outer_MAE_mean"] if c in g]
    if metric_cols:
        g = g.drop_duplicates(subset=metric_cols, keep="first")
    return g.iloc[0]


def table3_strict_performance(tables_root: Path, table1: pd.DataFrame) -> pd.DataFrame:
    path = tables_root / "Data_complete_5x5_metrics.csv"
    if not path.exists():
        path = tables_root / "TableS5_complete_5x5_metrics.csv"
    if not path.exists():
        raise FileNotFoundError(f"Run paper-tables first; missing {path}")
    metrics = read_csv_auto(path)
    n_map = dict(zip(table1["Task"], table1["Valid records (n)"]))
    rows: list[dict[str, object]] = []
    for task in MAIN_TASKS:
        r = _preferred_summary_row(metrics, task)
        if r is None:
            continue
        name = task_label(task).replace("$", "")
        base = {
            "Task": name,
            "n": n_map.get(name, np.nan),
            "Feature view": r.get("configured_current_view", ""),
            "K": "ALL" if pd.isna(r.get("configured_current_k", np.nan)) else int(float(r.get("configured_current_k"))),
            "Outer folds": int(float(r.get("outer_splits_completed", 5))) if not pd.isna(r.get("outer_splits_completed", 5)) else 5,
            "Primary metric": "Macro-F1" if task == "UL94_V0" else "R²",
        }
        if task == "UL94_V0":
            base.update({
                "Primary performance": _fmt(r.get("outer_Macro_F1_mean"), r.get("outer_Macro_F1_std")),
                "Accuracy": _fmt(r.get("outer_Accuracy_mean"), r.get("outer_Accuracy_std")),
                "Balanced accuracy": _fmt(r.get("outer_Balanced_Accuracy_mean"), r.get("outer_Balanced_Accuracy_std")),
                "ROC-AUC": _fmt(r.get("outer_ROC_AUC_mean"), r.get("outer_ROC_AUC_std")),
                "RMSE": "", "MAE": "",
            })
        else:
            base.update({
                "Primary performance": _fmt(r.get("outer_R2_mean"), r.get("outer_R2_std")),
                "RMSE": _fmt(r.get("outer_RMSE_mean"), r.get("outer_RMSE_std"), 2),
                "MAE": _fmt(r.get("outer_MAE_mean"), r.get("outer_MAE_std"), 2),
                "Accuracy": "", "Balanced accuracy": "", "ROC-AUC": "",
            })
        rows.append(base)
    return pd.DataFrame(rows)


def table4_robustness(tables_root: Path) -> pd.DataFrame:
    """Build main-text robustness table directly from frozen V5 FINAL results."""

    results_root = tables_root.parent

    split_path = (
        results_root
        / "scientific_validation"
        / "FINAL_grouping_sensitivity_5x5"
        / "scientific_nested_summary_all.csv"
    )

    bde_path = (
        results_root
        / "scientific_validation"
        / "FINAL_BDE_paired_ablation_5x5"
        / "scientific_nested_summary_all.csv"
    )

    if not split_path.exists():
        raise FileNotFoundError(
            f"Missing split-validation summary: {split_path}"
        )

    if not bde_path.exists():
        raise FileNotFoundError(
            f"Missing BDE summary: {bde_path}"
        )

    split = read_csv_auto(split_path)
    bde = read_csv_auto(bde_path)

    rows = []

    for task in CORE_ROBUSTNESS_TASKS:

        metric = "Macro-F1" if task == "UL94_V0" else "R²"

        row = {
            "Task": task_label(task).replace("$", ""),
            "Metric": metric,
        }

        # --------------------------------------------------------
        # Molecule / scaffold / reference split sensitivity
        # --------------------------------------------------------
        for split_name in [
            "molecule",
            "scaffold",
            "reference",
        ]:

            s = split[
                split["task"].astype(str).eq(task)
                & split["split_strategy"].astype(str).eq(split_name)
                & pd.to_numeric(
                    split["use_BDE"],
                    errors="coerce",
                ).fillna(0).eq(0)
            ]

            if s.empty:
                value = ""
            else:
                r = s.iloc[0]

                if task == "UL94_V0":
                    value = _fmt(
                        r.get("outer_Macro_F1_mean"),
                        r.get("outer_Macro_F1_std"),
                    )
                else:
                    value = _fmt(
                        r.get("outer_R2_mean"),
                        r.get("outer_R2_std"),
                    )

            row[f"{split_name.capitalize()} split"] = value

        # --------------------------------------------------------
        # With / without BDE
        # --------------------------------------------------------
        b = bde[
            bde["task"].astype(str).eq(task)
            & bde["split_strategy"].astype(str).eq("molecule")
        ]

        no_bde = b[
            pd.to_numeric(
                b["use_BDE"],
                errors="coerce",
            ).eq(0)
        ]

        with_bde = b[
            pd.to_numeric(
                b["use_BDE"],
                errors="coerce",
            ).eq(1)
        ]

        if task == "UL94_V0":
            metric_mean = "outer_Macro_F1_mean"
            metric_std = "outer_Macro_F1_std"
        else:
            metric_mean = "outer_R2_mean"
            metric_std = "outer_R2_std"

        if not no_bde.empty:
            r0 = no_bde.iloc[0]
            without_value = pd.to_numeric(
                pd.Series([r0.get(metric_mean)]),
                errors="coerce",
            ).iloc[0]

            row["Without BDE"] = _fmt(
                r0.get(metric_mean),
                r0.get(metric_std),
            )
        else:
            without_value = np.nan
            row["Without BDE"] = ""

        if not with_bde.empty:
            r1 = with_bde.iloc[0]
            with_value = pd.to_numeric(
                pd.Series([r1.get(metric_mean)]),
                errors="coerce",
            ).iloc[0]

            row["With BDE"] = _fmt(
                r1.get(metric_mean),
                r1.get(metric_std),
            )
        else:
            with_value = np.nan
            row["With BDE"] = ""

        if np.isfinite(without_value) and np.isfinite(with_value):
            row["Δ with−without BDE"] = (
                f"{with_value - without_value:+.3f}"
            )
        else:
            row["Δ with−without BDE"] = ""

        # --------------------------------------------------------
        # SHAP cross-fold rank stability
        # --------------------------------------------------------
        shap_path = (
            results_root
            / "05_Shap"
            / "FINAL_core_fixed_baseline_inclusive_5x5"
            / task
            / "molecule"
            / "formulation"
            / "without_BDE"
            / f"{task}_SHAP_rank_spearman.csv"
        )

        if shap_path.exists():

            corr = read_csv_auto(shap_path)

            matrix = (
                corr
                .drop(
                    columns=["outer_fold"],
                    errors="ignore",
                )
                .apply(
                    pd.to_numeric,
                    errors="coerce",
                )
                .to_numpy(dtype=float)
            )

            if (
                matrix.ndim == 2
                and matrix.shape[0] == matrix.shape[1]
            ):
                upper = matrix[
                    np.triu_indices_from(
                        matrix,
                        k=1,
                    )
                ]

                shap_mean = float(
                    np.nanmean(upper)
                )

                row["Mean SHAP rank Spearman"] = (
                    f"{shap_mean:.3f}"
                )
            else:
                row["Mean SHAP rank Spearman"] = ""

        else:
            row["Mean SHAP rank Spearman"] = ""

        rows.append(row)

    return pd.DataFrame(rows)


def table5_virtual_screening(tables_root: Path) -> pd.DataFrame:
    """Top-10 candidates from the final combined 35/50 stable priority set."""
    results_root = tables_root.parent
    path = (
        results_root
        / "06_ReverseDesign"
        / "FINAL_fixed"
        / "final_priority_combined"
        / "final_priority_candidates_combined.csv"
    )
    if not path.exists():
        raise FileNotFoundError(f"Missing final combined priority table: {path}")
    frame = read_csv_auto(path).copy()
    if "Final_priority_rank" in frame.columns:
        frame = frame.sort_values("Final_priority_rank")
    frame = frame.head(10).copy()

    out = pd.DataFrame({
        "Final cross-flux rank": frame.get("Final_priority_rank", pd.Series(range(1, len(frame)+1), index=frame.index)),
        "Candidate": frame.get("Candidate_Name", ""),
        "Design family": frame.get("Design_Family", ""),
        "Loading at 50 kW m⁻² (wt%)": frame.get("Loading_total_FR wt%_50", np.nan),
        "LOI pred. (%)": frame.get("LOI_pred_50", np.nan),
        "PHRR pred. at 50 kW m⁻²": frame.get("PHRR_pred_50", np.nan),
        "PHRR pred. at 35 kW m⁻²": frame.get("PHRR_pred_35", np.nan),
        "THR pred. at 50 kW m⁻² (MJ m⁻²)": frame.get("THR_pred_50", np.nan),
        "V-0 probability": frame.get("V0_probability_50", np.nan),
        "Tg pred. (°C)": frame.get("Tg_pred_50", np.nan),
        "TS pred. (MPa)": frame.get("TS_pred_50", np.nan),
        "Rank at 50": frame.get("Candidate_rank_50", np.nan),
        "Rank at 35": frame.get("Candidate_rank_35", np.nan),
    })

    # Publication-friendly numeric precision. Machine-readable full-precision
    # values remain available in Table S11 and the screening inventories.
    precision = {
        "Loading at 50 kW m⁻² (wt%)": 2,
        "LOI pred. (%)": 2,
        "PHRR pred. at 50 kW m⁻²": 2,
        "PHRR pred. at 35 kW m⁻²": 2,
        "THR pred. at 50 kW m⁻² (MJ m⁻²)": 2,
        "V-0 probability": 3,
        "Tg pred. (°C)": 2,
        "TS pred. (MPa)": 2,
    }
    for col, digits in precision.items():
        if col in out.columns:
            out[col] = pd.to_numeric(out[col], errors="coerce").round(digits)
    for col in ["Final cross-flux rank", "Rank at 50", "Rank at 35"]:
        if col in out.columns:
            out[col] = pd.to_numeric(out[col], errors="coerce").astype("Int64")
    return out.reset_index(drop=True)


def main() -> None:
    args = parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    df = read_csv_auto(args.data)

    t1 = table1_dataset_overview(df)
    t2 = table2_frozen_config(args.tables_root, args.task_config)
    t3 = table3_strict_performance(args.tables_root, t1)
    t4 = table4_robustness(args.tables_root)
    t5 = table5_virtual_screening(args.tables_root)

    outputs = [
        ("Table1_dataset_and_task_overview.csv", t1,
         "Dataset scale and prediction-task overview", "Data and methods"),
        ("Table2_frozen_model_configurations.csv", t2,
         "Frozen feature and validation configurations", "Machine-learning methods"),
        ("Table3_strict_nested_validation_performance.csv", t3,
         "Five-fold outer-test performance under strict nested grouped validation", "Results: predictive performance"),
        ("Table4_robustness_and_BDE_summary.csv", t4,
         "Grouping sensitivity, BDE ablation, and SHAP stability", "Results: robustness and interpretation"),
        ("Table5_top10_virtual_screening_candidates.csv", t5,
         "Top 10 candidates from the final combined 35/50 kW/m² stable screening", "Results: virtual screening"),
    ]
    manifest = []
    for filename, frame, caption, section in outputs:
        path = args.output / filename
        frame.to_csv(path, index=False, encoding="utf-8-sig")
        manifest.append({"table": filename.split("_")[0], "file": filename, "rows": len(frame),
                         "recommended_caption": caption, "recommended_section": section})
        print(f"[OK] {filename}: {len(frame)} rows")
    pd.DataFrame(manifest).to_csv(args.output / "main_text_table_manifest.csv", index=False, encoding="utf-8-sig")
    print(f"\n[DONE] Main-text tables: {args.output}")


if __name__ == "__main__":
    main()
